# Tugas 2

#SOAL

1.   Carilah data yang bertipe numerik ( data klassifikasi)
2.   Lakukan proses diskritisasi dengan equal width dan equal frequency
3.   Lakukan proses diskritisasi dengan basis entropy
4.   Kumpulkan tugas dengan link github ( web statis dari jupyter book)

In [1]:
#import library
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statistics as st
from scipy import stats

url="https://raw.githubusercontent.com/Amelia039/my-dataset/main/IRIS.csv"

c=pd.read_csv(url)
c

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

#Diskritisasi 
Merupakan proses mengubah data numerik yang bersifat kontinu menjadi data kategorik yang bersifat diskrit dengan mengelompokkan setiap data ke dalam interval-interval tertentu.
Terdapat 2 pendekatan:


*   Equal-width Intervals
Equal-width intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar. Dilakukan dengan membagi-bagi data ke dalam N buah interval (bins) dengan lebar (width) yang seragam antar interval.

*  Equal-frequency Intervals
Equal-frequency intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

##Equal-width Intervals

Menggunakan fungsi cut() untuk mencari interval menggunakan equal-width intervals

Sebagai contoh disini saya akan membagi menjadi 3 interval

In [2]:
labelsforlength=['pendek','sedang','panjang'] #Untuk label panjang
labelsforwidth=['kecil','sedang','lebar'] #Untukk label lebar

###sepal_length	: panjang sepal/panjangkelopak bunga iris dibagi menjadi 3 yakni pendek,sedang,dan panjang

In [3]:
eqwidth_sepal_length_intv = pd.cut(c['sepal_length'],3).value_counts()
eqwidth_sepal_length_intv

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal_length, dtype: int64

In [4]:

eqwidth_sepal_length = pd.cut(c['sepal_length'],3,labels=labelsforlength).value_counts()
eqwidth_sepal_length

sedang     71
pendek     59
panjang    20
Name: sepal_length, dtype: int64

In [5]:
a = pd.qcut(c['sepal_length'],3,labels=labelsforlength).value_counts()
a

sedang     56
pendek     52
panjang    42
Name: sepal_length, dtype: int64

In [6]:

sepal_length_bin = pd.cut(c['sepal_length'],len(labelsforlength), True, labelsforlength)
sepal_with_label = sepal_length_bin.value_counts()
pd.concat((c['sepal_length'],sepal_length_bin),axis=1)

    sepal_length sepal_length
0            5.1       pendek
1            4.9       pendek
2            4.7       pendek
3            4.6       pendek
4            5.0       pendek
..           ...          ...
145          6.7       sedang
146          6.3       sedang
147          6.5       sedang
148          6.2       sedang
149          5.9       sedang

[150 rows x 2 columns]

###Sepal Width : lebar sepal/ lebar kelopak bunga iris dibagi menjadi 3 yakni kecil,sedang,dan lebar

In [7]:
eqwidth_sepal_width_intv = pd.cut(c['sepal_width'],3).value_counts()
eqwidth_sepal_width_intv

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

In [8]:
labelsforwidth=['kecil','sedang','lebar']
eqwidth_sepal_width = pd.cut(c['sepal_width'],3,labels=labelsforwidth).value_counts()
eqwidth_sepal_width

sedang    88
kecil     47
lebar     15
Name: sepal_width, dtype: int64

In [9]:
sepal_width_bin = pd.cut(c['sepal_width'],len(labelsforwidth), True, labelsforwidth)
sepal_with_label = sepal_width_bin.value_counts()
pd.concat((c['sepal_width'],sepal_width_bin),axis=1)

    sepal_width sepal_width
0           3.5      sedang
1           3.0      sedang
2           3.2      sedang
3           3.1      sedang
4           3.6      sedang
..          ...         ...
145         3.0      sedang
146         2.5       kecil
147         3.0      sedang
148         3.4      sedang
149         3.0      sedang

[150 rows x 2 columns]

###petal length : panjang mahkota bunga iris dibagi menjadi 3 yakni pendek,sedang,dan panjang

In [10]:
eqwidth_petal_length_intv = pd.cut(c['petal_length'],3).value_counts()
eqwidth_petal_length_intv

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal_length, dtype: int64

In [11]:
eqwidth_petal_length = pd.cut(c['petal_length'],3,labels=labelsforlength).value_counts()
eqwidth_petal_length

sedang     54
pendek     50
panjang    46
Name: petal_length, dtype: int64

In [12]:
petal_length_bin = pd.cut(c['petal_length'],len(labelsforlength), True, labelsforlength)
petal_with_label = petal_length_bin.value_counts()
pd.concat((c['petal_length'],petal_length_bin),axis=1)

    petal_length petal_length
0            1.4       pendek
1            1.4       pendek
2            1.3       pendek
3            1.5       pendek
4            1.4       pendek
..           ...          ...
145          5.2      panjang
146          5.0      panjang
147          5.2      panjang
148          5.4      panjang
149          5.1      panjang

[150 rows x 2 columns]

###petal_width	: lebar petal/lebar mahkota bunga iris dibagi menjadi 3 yakni kecil,sedang,dan lebar

In [13]:
eqwidth_petal_width_intv = pd.cut(c['petal_width'],3).value_counts()
eqwidth_petal_width_intv

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal_width, dtype: int64

In [14]:
eqwidth_petal_width = pd.cut(c['petal_width'],3,labels=labelsforwidth).value_counts()
eqwidth_petal_width

sedang    54
kecil     50
lebar     46
Name: petal_width, dtype: int64

In [15]:

petal_width_bin = pd.cut(c['petal_width'],len(labelsforwidth), True, labelsforwidth)
petal_with_label = petal_length_bin.value_counts()
pd.concat((c['petal_width'],petal_width_bin),axis=1)

    petal_width petal_width
0           0.2       kecil
1           0.2       kecil
2           0.2       kecil
3           0.2       kecil
4           0.2       kecil
..          ...         ...
145         2.3       lebar
146         1.9       lebar
147         2.0       lebar
148         2.3       lebar
149         1.8       lebar

[150 rows x 2 columns]

##Equal-frequency Intervals
Menggunakan fungsi qcut() yang dapat digunakan untuk melakukan binning data. qcut digambarkan sebagai Quantile-based discretization function. 
Fungsi qcut() ini akan membagi data ke dalam jumlah yang sama.

###Sepal length

In [16]:
#Sepal length
eqfrequency_sepal_length_intv = pd.qcut(c['sepal_length'],3).value_counts()
eqfrequency_sepal_length_intv

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal_length, dtype: int64

In [17]:
eqfrequency_sepal_length = pd.qcut(c['sepal_length'],3,labels=labelsforlength).value_counts()
eqfrequency_sepal_length

sedang     56
pendek     52
panjang    42
Name: sepal_length, dtype: int64

In [18]:
sepal_length_bin = pd.qcut(c['sepal_length'],len(labelsforlength), labelsforlength)
sepal_with_label = sepal_length_bin.value_counts()
pd.concat((c['sepal_length'],sepal_length_bin),axis=1)

    sepal_length sepal_length
0            5.1       pendek
1            4.9       pendek
2            4.7       pendek
3            4.6       pendek
4            5.0       pendek
..           ...          ...
145          6.7      panjang
146          6.3       sedang
147          6.5      panjang
148          6.2       sedang
149          5.9       sedang

[150 rows x 2 columns]

In [19]:
#Sepal width

eqfrequency_sepal_width_intv = pd.qcut(c['sepal_width'],3).value_counts()
eqfrequency_sepal_width_intv

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepal_width, dtype: int64

In [20]:
eqfrequency_sepal_width = pd.qcut(c['sepal_width'],3,labels=labelsforlength).value_counts()
eqfrequency_sepal_width

pendek     57
sedang     51
panjang    42
Name: sepal_width, dtype: int64

In [21]:
sepal_width_bin = pd.qcut(c['sepal_width'],len(labelsforwidth), labelsforwidth)
sepal_with_label = sepal_width_bin.value_counts()
pd.concat((c['sepal_width'],sepal_width_bin),axis=1)

    sepal_width sepal_width
0           3.5       lebar
1           3.0      sedang
2           3.2      sedang
3           3.1      sedang
4           3.6       lebar
..          ...         ...
145         3.0      sedang
146         2.5       kecil
147         3.0      sedang
148         3.4       lebar
149         3.0      sedang

[150 rows x 2 columns]

In [22]:
#Petal length
eqfrequency_petal_length_intv = pd.qcut(c['petal_length'],3).value_counts()
eqfrequency_petal_length_intv

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal_length, dtype: int64

In [23]:

eqfrequency_petal_length = pd.qcut(c['petal_length'],3,labels=labelsforlength).value_counts()
eqfrequency_petal_length

sedang     54
pendek     50
panjang    46
Name: petal_length, dtype: int64

In [24]:

petal_length_bin = pd.qcut(c['petal_length'],len(labelsforlength), labelsforlength)
sepal_with_label = petal_length_bin.value_counts()
pd.concat((c['petal_length'],petal_length_bin),axis=1)

    petal_length petal_length
0            1.4       pendek
1            1.4       pendek
2            1.3       pendek
3            1.5       pendek
4            1.4       pendek
..           ...          ...
145          5.2      panjang
146          5.0      panjang
147          5.2      panjang
148          5.4      panjang
149          5.1      panjang

[150 rows x 2 columns]

In [25]:
#Petal width
eqfrequency_petal_width_intv = pd.qcut(c['petal_width'],3).value_counts()
eqfrequency_petal_width_intv

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal_width, dtype: int64

In [26]:

eqfrequency_petal_width = pd.qcut(c['petal_width'],3,labels=labelsforwidth).value_counts()
eqfrequency_petal_width

sedang    52
kecil     50
lebar     48
Name: petal_width, dtype: int64

In [27]:

petal_width_bin = pd.qcut(c['petal_width'],len(labelsforwidth), labelsforwidth)
sepal_with_label = petal_width_bin.value_counts()
pd.concat((c['petal_width'],petal_width_bin),axis=1)

    petal_width petal_width
0           0.2       kecil
1           0.2       kecil
2           0.2       kecil
3           0.2       kecil
4           0.2       kecil
..          ...         ...
145         2.3       lebar
146         1.9       lebar
147         2.0       lebar
148         2.3       lebar
149         1.8       lebar

[150 rows x 2 columns]

#Proses diskritisasi dengan basis entropy

Merupakan jenis algoritma diskritisasi terawasi yang menggunakan mekanisme top- down. 

Tujuan dari algoritma ini adalah mendapatkan partisi yang mengandung baris data dari kelas yang sama sebanyak mungkin.

Entropi pada umumnya digunakan
untuk mengukur ketidakpastian dari
sekumpulan atribut dari suatu set data.
Ukuran entropi dianggap sebagai
ukuran ketidakpastian dimana semakin
tinggi entropy suatu atribut maka
semakin tinggi ketidakpastian


*  Rumus Entropy

$$
\operatorname{Entropy}\left(D_1\right)=-\sum_{i=1}^m P i \log _2 P i
$$

*  Rumus Gain

$$
\operatorname{Gain}\left(E_{\text {new }}\right)=E_{\text {initial }}-E_{\text {new }}
$$


*  Rumus Info
$$
\operatorname{Info}_A(D)=\frac{\left|D_1\right|}{|D|} \operatorname{Entropy}\left(D_1\right)+\frac{\left|D_2\right|}{|D|} \operatorname{Entropy}\left(D_2\right)
$$

###Sampel data

In [28]:
sample=c[['sepal_length']]
sample.describe()

       sepal_length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

### Membuat Kategori

In [29]:

np.random.seed(0)
sample["kategori"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     sepal_length kategori
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

### Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [30]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("kategori").count()
  a = group.loc['A', col]
  b = group.loc["B", col]
  return (a,b,a+b)

### Memasukan fungsi splitter yang digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [31]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("kategori").count()
  greater_group = greater.loc[:, :].groupby("kategori").count()

  #get value based on category
  less_category_A = less_group.loc['A',col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc['A',col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

### Membuat fungsi entropy untuk melakukan perhitungan entropy (menggunakan rumus entropy)

In [32]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

### Membuat fungsi info

In [33]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

### Membuat fungsi gain

In [34]:
def gain(Einitial, Enew):
  return Einitial - Enew

### Membuat Dinitial

In [35]:
get_overoll = GetOverollCategory("sepal_length")
entropy_data = entropy(get_overoll)
print(get_overoll)
print(entropy_data)

(68, 82, 150)
0.993707106604508

### Melakukan beberapa split

In [36]:
split1 = splitter(5.5, "sepal_length")
info_split1 = info(split1)
gain(entropy_data, info_split1)

0.012302155146638905

In [37]:
split2 = splitter(6.5, "sepal_length")
info_split2 = info(split2)
gain(entropy_data, info_split2)

0.00012921701793400242

In [38]:
split3 = splitter(7, "sepal_length")
info_split3 = info(split3)
gain(entropy_data, info_split3)

0.0005490214732508658